#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Authen-NTLM
Version  : 1.09
Release  : 20
URL      : https://cpan.metacpan.org/authors/id/N/NB/NBEBOUT/NTLM-1.09.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/N/NB/NBEBOUT/NTLM-1.09.tar.gz
Summary  : ~
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-1.0
Requires: perl-Authen-NTLM-license = %{version}-%{release}
Requires: perl-Authen-NTLM-perl = %{version}-%{release}
Requires: perl(Digest::HMAC_MD5)
BuildRequires : buildreq-cpan
BuildRequires : perl(Digest::HMAC_MD5)

%description
NTLM Authentication Scheme
==========================
This module implements the NTLM authentication mechanism.  It can be
used to perform NTLM style authentication for any desired protocol.

%package dev
Summary: dev components for the perl-Authen-NTLM package.
Group: Development
Provides: perl-Authen-NTLM-devel = %{version}-%{release}
Requires: perl-Authen-NTLM = %{version}-%{release}

%description dev
dev components for the perl-Authen-NTLM package.


%package license
Summary: license components for the perl-Authen-NTLM package.
Group: Default

%description license
license components for the perl-Authen-NTLM package.


%package perl
Summary: perl components for the perl-Authen-NTLM package.
Group: Default
Requires: perl-Authen-NTLM = %{version}-%{release}

%description perl
perl components for the perl-Authen-NTLM package.


%prep
%setup -q -n NTLM-1.09
cd %{_builddir}/NTLM-1.09

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Authen-NTLM
cp %{_builddir}/NTLM-1.09/COPYING-Artistic %{buildroot}/usr/share/package-licenses/perl-Authen-NTLM/a832d4d06f91db191b4f336e98016f0bc5bf9879
cp %{_builddir}/NTLM-1.09/COPYING-GPL %{buildroot}/usr/share/package-licenses/perl-Authen-NTLM/7aba5bad3f07e795b696a206f5655dc5dcfd1b8c
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Authen::NTLM.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Authen-NTLM/7aba5bad3f07e795b696a206f5655dc5dcfd1b8c
/usr/share/package-licenses/perl-Authen-NTLM/a832d4d06f91db191b4f336e98016f0bc5bf9879

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
